
const mt=document.getElementById('menuToggle');if(mt)mt.addEventListener('click',()=>{const a=document.getElementById('app');if(innerWidth<=980)a.classList.toggle('mobile-open');else a.classList.toggle('collapsed')});
function openModal(t,h){document.getElementById('modalTitle').textContent=t;document.getElementById('modalBody').innerHTML=h;document.getElementById('modal').classList.add('open')}
function closeModal(){document.getElementById('modal').classList.remove('open')}
document.getElementById('modal')?.addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
function toast(m){alert(m)}
function formReady(){return `<div class="form-grid"><div class="field"><label>ผลตรวจ</label><select><option>ผ่าน</option><option>ไม่ผ่าน</option></select></div><div class="field"><label>วันที่ตรวจ</label><input type="date"></div><div class="field full"><label>หมายเหตุ</label><textarea rows="3"></textarea></div></div><div class="actions"><span></span><button class="btn btn-primary" onclick="toast('บันทึกเรียบร้อย');closeModal()">บันทึก</button></div>`}
function uploadForm(){return `<div class="field"><label>เลือกเอกสาร PDF/JPG</label><input type="file" multiple accept=".pdf,.jpg,.jpeg,.png"></div><div class="actions"><span></span><button class="btn btn-primary" onclick="toast('อัปโหลดสำเร็จ');closeModal()">อัปโหลด</button></div>`}
function confirmSend(f){return `<p>ยืนยันส่งแบบฟอร์ม ${f} เข้าสู่กระบวนการตรวจสอบหรือไม่</p><div class="notice">เมื่อส่งแล้ว หากต้องการแก้ไขต้องให้ผู้ตรวจส่งกลับ</div><div class="actions"><button class="btn btn-secondary" onclick="closeModal()">ยกเลิก</button><button class="btn btn-primary" onclick="toast('ส่ง ${f} แล้ว');closeModal()">ยืนยันส่ง</button></div>`}
function reviewForm(f){return `<div class="notice">ตรวจข้อมูลและเอกสาร ${f} ครบถ้วน 6/6 รายการ</div><div class="field"><label>Checklist</label><textarea rows="5">✓ ข้อมูลนักศึกษาถูกต้อง
✓ คุณสมบัติผ่านเกณฑ์
✓ เอกสารแนบครบ
✓ ลายมือชื่อครบ</textarea></div><div class="field"><label>ความเห็น</label><textarea rows="3"></textarea></div><div class="actions"><button class="btn btn-warn" onclick="toast('ส่งกลับแก้ไขแล้ว');closeModal()">ส่งกลับแก้ไข</button><button class="btn btn-success" onclick="toast('อนุมัติแล้ว');closeModal()">อนุมัติ</button></div>`}
function approveForm(f){return reviewForm(f)}
function companyConfirm(){return `<div class="form-grid"><div class="field"><label>ตำแหน่งงาน</label><input value="Software Developer Intern"></div><div class="field"><label>พี่เลี้ยง</label><input value="ศิริพร ใจดี"></div><div class="field"><label>วันที่เริ่ม</label><input type="date" value="2026-11-01"></div><div class="field"><label>วันที่สิ้นสุด</label><input type="date" value="2027-02-28"></div><div class="field full"><label>เงื่อนไข/หมายเหตุ</label><textarea rows="3"></textarea></div></div><div class="actions"><button class="btn btn-danger" onclick="toast('ปฏิเสธแล้ว');closeModal()">ไม่รับ</button><button class="btn btn-success" onclick="toast('ยืนยันรับนักศึกษาแล้ว');closeModal()">ยืนยันรับ</button></div>`}
function logbookForm(){return `<div class="form-grid"><div class="field"><label>สัปดาห์</label><input type="number" value="9"></div><div class="field"><label>ช่วงวันที่</label><input type="date"></div><div class="field full"><label>งานที่ดำเนินการ</label><textarea rows="4"></textarea></div><div class="field full"><label>ไฟล์แนบ</label><input type="file" multiple></div></div><div class="actions"><span></span><button class="btn btn-primary" onclick="toast('บันทึก Logbook แล้ว');closeModal()">บันทึก</button></div>`}
function calendarForm(){return `<div class="form-grid"><div class="field"><label>นักศึกษา</label><select><option>กมลชนก วัฒนชัย</option></select></div><div class="field"><label>รูปแบบ</label><select><option>On-site</option><option>Online</option></select></div><div class="field"><label>วันที่</label><input type="date"></div><div class="field"><label>เวลา</label><input type="time"></div><div class="field"><label>ระยะเวลา (นาที)</label><input type="number" value="60"></div><div class="field"><label>Buffer (นาที)</label><input type="number" value="15"></div></div><div class="actions"><span></span><button class="btn btn-primary" onclick="toast('สร้างนัดแล้ว');closeModal()">สร้างนัด</button></div>`}
function visitForm(){return `<div class="field"><label>ผลการนิเทศ</label><select><option>ดีมาก</option><option>ดี</option><option>ต้องปรับปรุง</option></select></div><div class="field"><label>รายละเอียด</label><textarea rows="5"></textarea></div><div class="actions"><span></span><button class="btn btn-primary" onclick="toast('บันทึกผลนิเทศแล้ว');closeModal()">บันทึก</button></div>`}
function evaluationForm(who){return `<p>ผู้ประเมิน: <b>${who}</b></p><table><tr><th>หัวข้อ</th><th>คะแนนเต็ม</th><th>คะแนน</th></tr><tr><td>ความรู้และทักษะวิชาชีพ</td><td>30</td><td><input type="number" value="26" min="0" max="30"></td></tr><tr><td>ความรับผิดชอบและวินัย</td><td>25</td><td><input type="number" value="23"></td></tr><tr><td>การสื่อสารและทำงานเป็นทีม</td><td>25</td><td><input type="number" value="22"></td></tr><tr><td>ผลงาน/รายงาน</td><td>20</td><td><input type="number" value="17"></td></tr></table><div class="field"><label>ข้อเสนอแนะ</label><textarea rows="3"></textarea></div><div class="actions"><span></span><button class="btn btn-primary" onclick="toast('บันทึกผลประเมินแล้ว');closeModal()">บันทึกผล</button></div>`}
function closeProject(){return `<p>ยืนยันปิดโครงการสหกิจศึกษาของนักศึกษารายนี้?</p><div class="field"><label>หมายเหตุการปิดโครงการ</label><textarea rows="3"></textarea></div><div class="notice">ระบบจะบันทึกผู้ดำเนินการ วันเวลา ผลคะแนน และเอกสารทั้งหมดใน Audit Log</div><div class="actions"><button class="btn btn-secondary" onclick="closeModal()">ยกเลิก</button><button class="btn btn-success" onclick="toast('ปิดโครงการแล้ว');closeModal()">ยืนยันปิดโครงการ</button></div>`}
